[package]
name = "barest"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader="0.9.29"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.9"
volatile = "0.2"

[build-dependencies]
bootimage = "0.10"

[package.metadata.bootloader]
target = "x86_64-unknown-none"  

